### PR TITLE
Fix incorrect error message when searching with no results

### PR DESCRIPTION
**Pull request by curtgrimes**
Previously, when searching for videos and getting no results back, the message "An error occurred. Please make sure you're connected to the internet and try again." would always appear.

Now, the message "No video results available." will appear instead, as long as there are no issues with the network connection.

## Before

Screenshot-StemRoller-2024-03-09-11-28-48

## After

Screenshot-StemRoller-2024-03-09-11-44-54

### CODE REVIEW

**Comment by curtgrimes** [comment]
Hi @iffyloop - did you have any feedback for this PR? Is there a way it could be made better, or are you not looking for this type of contribution? StemRoller has been a big time saver for me -- thank you for your great work!

**Comment by iffyloop** [comment]
Hey @curtgrimes I'm really sorry, I don't remember closing this so am not sure what happened, but I think I deleted the `develop` branch and so perhaps GitHub automatically closed this PR? Very frustrating. Will merge and trigger a new update ASAP.

**Review by iffyloop — APPROVED** [review]

**Comment by iffyloop** [comment]
Looks like I messed everything up with the commit history, am still somewhat new to Git so thanks for your patience and for pinging me earlier when the PR was closed unintentionally. Thank you for contributing, @curtgrimes!

**Comment by curtgrimes** [comment]
Thank you! No worries. I appreciate your work with this. I took a peek at the commit history and it looks like it's back on track now. Thanks again!

**Pull request merged**
